apiVersion: v1
kind: Pod
metadata:
  name: probe-pod
spec:
  containers:
  - name: container1
    image: yasirdocker/flag:latest
    ports:
    - containerPort: 80
    livenessProbe:
      exec:
        command:
        - ls
      initialDelaySeconds: 2
      periodSeconds: 10
    readinessProbe:
      exec:
        command:
        - ls
      initialDelaySeconds: 5
      periodSeconds: 10