# ************* Section (a) ************* 
apiVersion: v1

# ************* Section (b) ************* 
kind: Pod

# ************* Section (c) ************* 
metadata:
  name: pod1

# ************* Section (d) ************* 
spec:
  containers:
  - name: container1
    image: ubuntu           # <-- changed image
    command: ["sleep"]      # <-- run sleep command
    args: ["200000"]            # <-- sleep for 20 seconds