apiVersion: v1

kind: Pod

metadata: 
  name: podwithnodeselector3

spec:
  nodeSelector:
    processor: i9
  containers:
  - name: container1
    image: yasirdocker/flag:latest
    ports:
    - containerPort: 80
