# ************* Section (a) ************* 
apiVersion: v1

# ************* Section (b) ************* 
kind: Pod

# ************* Section (c) ************* 
metadata:
  name: myfirstpod

# ************* Section (d) ************* 
spec:
  containers:
  - name: container1
    image: yasirdocker/flag:latest
    ports: 
      - containerPort: 80