apiVersion: v1

kind: Pod

metadata:
  name: firstpodwithlabels
  labels:
    type: backend
    city: khi
    env: production

spec:
  containers:
  - image: yasirdocker/flag:latest
    name: container1
    ports:
    - containerPort: 80